apache/cayenne

cayenne-server/src/main/java/org/apache/cayenne/datasource/DataSourceBuilder.java

"cayenne.jdbc.max_connections" and "cayenne.jdbc.min_connections" command line options are ignored. Regardless of provided values Cayenne uses default values cayenne.jdbc.max_connections = 1 and cayenne.jdbc.min_connections = 1.

CAY-2041 max_connections and min_conneсtions options are ignored

---

cayenne-server/src/main/java/org/apache/cayenne/reflect/BeanAccessor.java
cayenne-server/src/test/java/org/apache/cayenne/reflect/BeanAccessorTest.java
cayenne-server/src/test/java/org/apache/cayenne/reflect/TstHasRelated.java
cayenne-server/src/test/java/org/apache/cayenne/reflect/TstJavaBeanChild.java

In certain cases, simply adding an interface to a class with no other changes can break `PropertyUtils.setProperty`.
For example, consider a HasName interface and a Person entity with a name attribute:
```java
public interface HasName {
CharSequence getName();
}
```
```java
public class _Person extends CayenneDataObject {
public void setName(String name) {
writeProperty(NAME_KEY, name);
}
public String getName() {
return (String) readProperty(NAME_KEY);
}
}
```
```java
public class Person extends _Person implements HasName {
}
```
My only change from the generated classes is to make `Person` implement `HasName`. Now, when I call `PropertyUtils.setProperty(person, Person.NAME_KEY, newName)`, I get a `PropertyException: Property "name" is not writable`.
What's happening is that the compiler …

Fix BeanAccessors for Classes with Complex Inheritance

---

cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DefaultValueTransformerFactory.java
cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DoubleConverter.java
cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/FloatConverter.java
cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/IntegerConverter.java
cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/LongConverter.java
cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/ShortConverter.java
cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/DoubleConverterTest.java
cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/FloatConverterTest.java

Includes float and double converters + fix for numeric overflow in short, integer and long converters

Cayenne-crypto: support for mapping non-String and non-binary types

---

cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DefaultValueTransformerFactory.java

bindings for primitive boolean

CAY-2103 cayenne-crypto: support for mapping non-String and non-binary types

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CustomModePanel.java

Set "overwrite" checkbox inactive when "make pair" checkbox is selected as it has no effect in this case.

Modeler. Advanced class generation menu enhancement

---

cayenne-project/src/main/java/org/apache/cayenne/project/upgrade/v8/UpgradeHandler_V8.java
cayenne-server/src/main/java/org/apache/cayenne/map/MapLoader.java
cayenne-server/src/main/java/org/apache/cayenne/map/QueryDescriptorLoader.java
docs/doc/src/main/resources/RELEASE-NOTES.txt

Fix notes: this is a hot-fix for exact problem converting queries from v6 directly to v9 format.
Actually whole upgrade system should be redesigned, see some thoughts at https://issues.apache.org/jira/browse/CAY-2152

CAY-2148 Failure upgrading from 3.1 to M4

---

cayenne-project/src/main/java/org/apache/cayenne/project/validation/ObjAttributeValidator.java
cayenne-server/src/main/java/org/apache/cayenne/map/ObjAttribute.java
docs/doc/src/main/resources/RELEASE-NOTES.txt
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/db/DbLoaderHelper.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/wrapper/ObjAttributeWrapper.java

After reverse engineering is done all data map is checked for invalid references from Obj to Db attributes
Additionally some defensive code added to bypass invalid db path state in ObjAttribute:
- correct check for this state in ObjAttribute validator
- returning null in ObjAttributeWrapper in modeler
- unconditional saving of db attribute path to XML (this one is questionable though)

CAY-2153 Modeler. Exception in save action after reverse engineering some complex DB schema

---

cayenne-server/src/main/java/org/apache/cayenne/map/EJBQLQueryDescriptor.java
cayenne-server/src/main/java/org/apache/cayenne/map/ProcedureQueryDescriptor.java
cayenne-server/src/main/java/org/apache/cayenne/map/QueryDescriptor.java
cayenne-server/src/main/java/org/apache/cayenne/map/SQLTemplateDescriptor.java
cayenne-server/src/main/java/org/apache/cayenne/map/SelectQueryDescriptor.java

It was possible to corrupt DataMap xml file with empty Cache Groups setting in query.

Modeler. Safe encode to XML query descriptors properties.

---

.travis.yml
cayenne-server/src/test/resources/simplelogger.properties

Enable travis

---

cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/merge/DbMerger.java
cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/merge/TokenComparator.java
cayenne-dbsync/src/test/java/org/apache/cayenne/dbsync/merge/DbMergerTest.java
cayenne-dbsync/src/test/java/org/apache/cayenne/dbsync/merge/MergeCase.java
cayenne-dbsync/src/test/java/org/apache/cayenne/dbsync/merge/TokenComparatorTest.java
cayenne-tools/src/main/java/org/apache/cayenne/tools/dbimport/DefaultDbImportAction.java
cayenne-tools/src/test/java/org/apache/cayenne/tools/dbimport/DefaultDbImportActionTest.java
docs/doc/src/main/resources/RELEASE-NOTES.txt
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/db/MergerTokenSelectorController.java

Real problem here is sorting order of MergeTokens.
In this fix:
- Improved sort on DbImportAction
- Added sorting to DB migration
Whole sorting need to be reviewed and possibly rewritten.

CAY-2016 cdbimport: Rename table with toMany relationship causes migration error

---

.travis.yml
cayenne-server/src/test/resources/simplelogger.properties
pom.xml

Since travis supports docker inside build, we can enable docker profiles.
Also i renamed `postgresdocker` to `postgres-docker` for consistency with `mysql-docker`

Enable docker profiles on travis.

---

framework/cayenne-jdk1.5-unpublished/src/main/java/org/apache/cayenne/dba/JdbcPkGenerator.java

Hi all, I noticed an issue with Frontbase primary key generation, the fix is really simple. There is a method getPkCacheSize() that is supposed to be overriden by subclasses, but we was calling the default value instead of method.

Fix issue with Frontbase PK generation

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/DBWizardAction.java

Modified connection.getSchema() call to be wrapped in try/catch block with a warning to the log.  In Sybase, getSchema() throws an Error because technically a schema isn't a valid concept.  The closest comparison in Sybase is the owner of the object (usually "dbo").  In this case, "currentSchema" will be null (which doesn't appear to have any consequences).

Reverse Engineering doesn't work with Sybase

---

docs/docbook/cayenne-guide/src/docbkx/setup.xml

CAY-1980 "maven-cayenne-modeler-plugin" renamed to "cayenne-modeler-maven-plugin"

 document updates for cayenne modeler based on 4.0.M5 changes

---

cayenne-server/src/main/java/org/apache/cayenne/exp/Property.java
cayenne-server/src/main/java/org/apache/cayenne/query/Ordering.java
cayenne-server/src/main/java/org/apache/cayenne/query/Orderings.java

I have added this class as a convenience to chain Ordering calls and then passing them into APIs that support List\<Ordering>.  Here's an example:
Person.COMPANY_NAME.asc().then(Person.LAST_NAME.desc()).then(Person.FIRST_NAME.asc())
I understand the the newer select API doesn't really need this, but there are still plenty of APIs that use List\<Ordering> and this newer format supports the code being simpler and easier to read.

Added the Orderings class to support chaning of asc() through Ordering

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/undo/RemoveRelationshipUndoableEdit.java

Added method `focusObjEntity(ObjEntity objEntity)` in `RemoveRelationshipUndoableEdit` class, that is called during `undo()` action in order to fix CAY-2384

CAY-2384  Modeler: Visualization issue after an undo action for a deleted ObjRelationship

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/DbEntityCounterpartAction.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/ObjEntityCounterpartAction.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/undo/CayenneUndoableEdit.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/undo/RemoveAttributeUndoableEdit.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/undo/RemoveRelationshipUndoableEdit.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/CayenneAction.java

Includes solution for both bugs [CAY-2385](https://issues.apache.org/jira/browse/CAY-2385) and [CAY-2386](https://issues.apache.org/jira/browse/CAY-2386), as well as the required refactoring derived from the solutions for [CY-2379](https://issues.apache.org/jira/browse/CAY-2379) and [CAY-2383](https://issues.apache.org/jira/browse/CAY-2383)
No bugs detected for `Embeddable` undo actions.

CAY-2385 CAY-2386 Fixing visualization issues after an undo action for a deleted DbRelationship or DbAttribute

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CustomModeController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CustomModePanel.java

Added update state of Superclass and Subclass Templates dropdowns on dialog open. Added disabling Subclass Template dropdown and added using singleclass.vm template when 'Make Pairs' checkbox is nod checked.

CAY-2476 Modeller: Fixed wrong bihaviour of code generation dialog

---

cayenne-server/src/main/java/org/apache/cayenne/access/DataDomainQueryAction.java
cayenne-server/src/main/java/org/apache/cayenne/query/ColumnSelect.java
cayenne-server/src/main/java/org/apache/cayenne/query/ColumnSelectMetadata.java
cayenne-server/src/main/java/org/apache/cayenne/query/QueryMetadata.java
cayenne-server/src/main/java/org/apache/cayenne/query/SQLSelect.java
cayenne-server/src/main/java/org/apache/cayenne/query/SQLTemplate.java
cayenne-server/src/main/java/org/apache/cayenne/query/SQLTemplateMetadata.java
cayenne-server/src/main/java/org/apache/cayenne/reflect/PojoMapper.java
cayenne-server/src/test/java/org/apache/cayenne/query/ColumnSelectIT.java
cayenne-server/src/test/java/org/apache/cayenne/query/SQLSelectIT.java
cayenne-server/src/test/java/org/apache/cayenne/reflect/PojoMapperTest.java

This PR adds simple `map(Function<T,R> mapper)` method to all fluent queries that can return `Object[]` result.
Usage example:
```java
class ArtistDTO {
ArtistDTO(Object[]) {
// ...
}
}
// ...
List<ArtistDTO> result = ObjectSelect.columnQuery(Artist.class, Artist.ARTIST_NAME, Artist.DATE_OF_BIRTH)
.map(ArtistDTO::new)
.select(context);
```

CAY-2527 Map Object[] result to pojo

---

cayenne-client/src/main/java/org/apache/cayenne/remote/hessian/ClientSerializerFactory.java
cayenne-client/src/main/java/org/apache/cayenne/rop/HttpClientConnectionProvider.java
cayenne-client/src/test/java/org/apache/cayenne/rop/http/HessianROPSerializationServiceIT.java
cayenne-rop-server/src/main/java/org/apache/cayenne/configuration/rop/server/ROPServerModule.java
cayenne-rop-server/src/main/java/org/apache/cayenne/remote/hessian/HessianConfig.java
cayenne-rop-server/src/main/java/org/apache/cayenne/rop/ROPConstants.java
cayenne-rop-server/src/main/java/org/apache/cayenne/rop/ServerHessianSerializationServiceProvider.java
pom.xml

This PR updates the Hessian version and enables whitelist only serialization.

Use whitelist for Hessian serialization

---

cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/reverse/dbload/RelationshipLoader.java

If there is no explicit database import configuration (e.g. included or excluded tables) then the database import may fail with a NullPointerException when 'Skip relationship loading' is *not* activated. When relationships are skipped, the import succeeds.
Check if `sourceTableFilter` in `RelationshipFilter.checkAndAddRelationship(DbEntity, DbRelationship` is null and skip then the include check (under the assumption that then all relationships should get imported).

Exception in dbimport when relationships should be imported, but no explicit configuration exists

---

cayenne-cgen/src/main/java/org/apache/cayenne/gen/DataMapUtils.java

Cgen should generate a `perform`-method for queries with qualifiers (e.g. `username = $ausername`) stored in the datamap, but there is no method generated. Queries without qualifiers get such a method.
If the alias map for `Entity.lastPathComponent(Expression, Map)` is null then an exception is thrown later in the constructor of `org.apache.cayenne.map.PathComponentIterator` at the line 
```
this.aliasMap = Objects.requireNonNull(aliasMap)
```
This means the qualifier is seen as invalid and therefore no `perform`-method is generated.

No methods for queries with qualifier parameters generated

---

cayenne-server/src/main/java/org/apache/cayenne/ObjectIdTmp.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/DefaultDataDomainFlushAction.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/EffectiveOpId.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/IdGenerationMarker.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/PermanentObjectIdVisitor.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/ReplacementIdVisitor.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/RootRowOpProcessor.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/operation/BaseDbRowOp.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/operation/DbRowOpGraph.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/operation/DbRowOpMerger.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/operation/DeleteDbRowOp.java
cayenne-server/src/main/java/org/apache/cayenne/access/flush/operation/GraphBasedDbRowOpSorter.java
cayenne-server/src/main/java/org/apache/cayenne/access/sqlbuilder/sqltree/ValueNode.java
cayenne-server/src/main/java/org/apache/cayenne/query/BatchQueryRow.java
cayenne-server/src/test/java/org/apache/cayenne/access/DataContextEntityWithMeaningfulPKIT.java
cayenne-server/src/test/java/org/apache/cayenne/access/flush/EffectiveOpIdTest.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/meaningful_pk/auto/_MeaningfulPKDep.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/meaningful_pk/auto/_MeaningfulPKTest1.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/meaningful_pk/auto/_MeaningfulPk.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/meaningful_pk/auto/_MeaningfulPkTest2.java
cayenne-server/src/test/resources/cayenne-meaningful-pk.xml
cayenne-server/src/test/resources/compound.map.xml
cayenne-server/src/test/resources/meaningful-pk.map.xml

This is an experimental implementation of a Db operations sorter that builds a directed graph and uses topological sort to get the final order of operations. 
This sorter can correctly order meaningful PK intersections (i.e. delete/insert rows with the same primary keys). 
Moreover, it opens a possibility to automatically break cycles in DB operations.

Experimental graph-based db operations sorter

---

cayenne-server/src/main/java/org/apache/cayenne/access/jdbc/SQLTemplateAction.java
cayenne-server/src/main/java/org/apache/cayenne/dba/frontbase/FrontBaseActionBuilder.java
cayenne-server/src/main/java/org/apache/cayenne/dba/frontbase/FrontBaseAdapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/frontbase/FrontBaseTemplateAction.java

FronBase jdbc driver incorrectly returns null instead of statement (or throwing SQLException at least) when connection.prepareStatement(sql, Statement.NO_GENERATED_KEYS) is called.
Driver just call connection.prepareStatement(sql), if dbAdapter is the FrontBaseAdapter.

fixed return of statement when using FrontBase DB

---

cayenne-server/src/main/java/org/apache/cayenne/value/Json.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/AbstractJsonConsumer.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/JsonFormatter.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/JsonReader.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/JsonTokenizer.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/JsonUtils.java
cayenne-server/src/main/java/org/apache/cayenne/value/json/MalformedJsonException.java
cayenne-server/src/test/java/org/apache/cayenne/value/json/JsonReaderTest.java
cayenne-server/src/test/java/org/apache/cayenne/value/json/JsonTokenizerTest.java
cayenne-server/src/test/java/org/apache/cayenne/value/json/JsonUtilsTest.java

This PR contains a simple JSON parser that could be used to normalize and compare JSON values to exclude time-consuming SQL updates caused by different formatting of JSON strings.
JSON parser is not intended for any other use-cases except for fast values comparison.
Here are simple benchmark results comparing Cayenne's specialized implementation with some widely used libraries.
Compare call in all cases is basically parsing two values + equals() call.
```
Benchmark                         Mode  Cnt   Score   Error  Units
GsonBenchmark.compare             avgt   12  89.533 ± 1.483  us/op
GsonBenchmark.read                avgt   12  39.398 ± 0.271  us/op
JacksonBenchmark.compare          avgt   12  80.887 ± 0.358  us/op
JacksonBenchmark.read             avgt   12  38.201 ± 0.347  us/op …
```

Utils for the JSON values comparison

---

cayenne-server/src/main/java/org/apache/cayenne/dba/AutoAdapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/DbAdapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/JdbcAdapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerActionBuilder.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerAdapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerSelectAction.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerSniffer.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerTreeProcessor.java
cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/sqltree/SQLServerLimitOffsetNode.java

Now cayenne query for SQLServer Limit/Offset converts to 'top (Limit+Offset)'.
I think we should convert it to:
OFFSET n ROWS
FETCH NEXT k ROWS ONLY;
If MS SQL Server 2008 and older is used, the query is converted to top (Limit+Offset)'. OFFSET can only be used with 'orderBy'.

CAY-2587 SQLServer Limit Offset convertation

---

cayenne-gradle-plugin/build.gradle
cayenne-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
cayenne-gradle-plugin/pom.xml
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/BaseCayenneTask.java
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/CgenTask.java
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/DbGenerateTask.java
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/DbImportTask.java
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/GradlePluginClassLoaderManager.java
cayenne-gradle-plugin/src/test/java/org/apache/cayenne/tools/GradlePluginIT.java
cayenne-gradle-plugin/src/test/resources/org/apache/cayenne/tools/dbimport-with-project-dependency.gradle

- Replace 4.8.1 Gradle version with 7.0 in path to binary file. 
_(cayenne-gradle-plugin/gradle/wrapper/gradle-wrapper.properties)_
- Replace 'compile' configuration with 'implementation' in build.gradle and test Gradle files due to 'compile' configuration is not supported yet. Where it is needed, resolvable=true property was set to 'implementation' in test files.
_(cayenne-gradle-plugin/build.gradle, cayenne-gradle-plugin/src/test/resources/org/apache/cayenne/tools/dbimport-with-project-dependency.gradle)_
- Gradle Api 7.0 requires getters and the lack of Optional annotation for fields marked with Input annotation, so these methods were added.
_(cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/CgenTask.java, cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/CgenTask …

CAY-2708 Gradle build plugin fails

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/LoadDbSchemaAction.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbimport/DatabaseSchemaLoader.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbimport/DbImportTree.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbimport/PrintColumnsBiFunction.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbimport/tree/TableNode.java

Previous logic didn't support tables outside schemes and catalogs. So, loading of tables on the root level and necessary functional were added.
- add trying to load tables if lists of schemes and catalogs of database were empty.
- root node has null path. So was added ability to get parent object of current node with null path (which will be null).
- container of tables can be null, because tables now can be placed outside schemes or catalogs on the root level. So, if container is null, common database container will be in use.
- add check if lists of schemes and catalogs are empty but tables are present, in that case will be created (but not printed) scheme with all tables of database, which will be transferred to next methods. This scheme can't be found in tree, so if it's container …

CAY-2699 modeler dbimport schema view not working

---

cayenne-server/src/main/java/org/apache/cayenne/tx/BaseTransaction.java
cayenne-server/src/main/java/org/apache/cayenne/tx/TransactionDescriptor.java
cayenne-server/src/main/java/org/apache/cayenne/tx/TransactionListener.java
cayenne-server/src/test/java/org/apache/cayenne/configuration/server/ServerRuntimeIT.java
cayenne-server/src/test/java/org/apache/cayenne/tx/DefaultTransactionManagerIT.java
cayenne-server/src/test/java/org/apache/cayenne/tx/TransactionCustomConnectionIT.java
cayenne-server/src/test/java/org/apache/cayenne/tx/TransactionIsolationIT.java
cayenne-server/src/test/java/org/apache/cayenne/tx/TransactionPropagationRollbackIT.java

- add connection supplier to TransactionDescriptor, if it presents, BaseTransaction provides only that connection
- add builder for TransactionDescriptor, mark constructors as deprecated and replace them in tests
- add ability to decorate connection from listeners with default method
- fix bugs in tests related to default methods in interfaces were not allowed
- add integration tests for added abilities

CAY-2637 allow forcing custom connection for transaction

---

cayenne-server/src/test/java/org/apache/cayenne/access/NestedDataContextWriteIT.java

This one is strange. It seems to work correctly on older versions, but not
all the time, maybe 25% only. But it seems to always fail now.
In any case, I would expect this operation to always succeed.

Add failing test for using a nested context with a two-stage commit

---

cayenne-protostuff/pom.xml

Tests in protostuff module will warn when using jdk 9 and later and will fail when using jdk 17 and later.
It happened because of an unnamed module.
It was resolved by adding a profile in pom.xml for java version 9 and later.

CAY-2711 JDK 17 compatibility

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/objentity/ObjRelationshipInfo.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/ProjectUtil.java

After relationship name editing is created duplicate of the relationship with the same name.  It happened because of add to map collection relationship entity with a different key. It resolves with checking for uniqueness and removing the same objects in the map before changing the key.

CAY-2724 Duplicating relationship after editing its name

---

cayenne-cgen/src/main/java/org/apache/cayenne/gen/CgenConfiguration.java

Solution for problem with slahses in .xml on different platforms

CAY-2727 modeler cgen destDir  Unix platform path separator 

---

cayenne-server/src/main/java/org/apache/cayenne/dba/h2/H2Adapter.java
cayenne-server/src/main/java/org/apache/cayenne/dba/h2/H2CharType.java

In Cayenne 4.1.1 (and probably other versions) when using CLOB's with H2 v2.0.202 an error occurs when attempting to save.
This is due to a change in behaviour in H2 (likely from 1.x) where a CLOB now needs to be saved as a stream.
When the statement.setString(pos, value) gets executed in Cayenne an exception is thrown from H2 as you now need to set a stream as follows:
Clob clob = st.getConnection().createClob();
clob.setString(1, val);
st.setClob(pos, clob);
This PR is to implement that behaviour into H2 clob handling.

Fix H2 clob streaming

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/CodeTemplateManager.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/TemplateCreator.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/CustomModeController.java

The solution for the issue with the missing custom templates. Now, if there is no template in the configuration, a template is created with the name, like a name of file specified in datamap.xml with an ordinal number attached to it (_for an example /templates/CustomTemplate.vm. will create template with name CustomTemplate_0)._
When generating classes (if the template file is missing), an error message will be displayed indicating the path to it.

CAY-2733 Modeler can't use custom templates set in a datamap

---

cayenne-server/src/main/java/org/apache/cayenne/access/HierarchicalObjectResolver.java
cayenne-server/src/main/java/org/apache/cayenne/access/JoinedIdParentAttachmentStrategy.java
cayenne-server/src/main/java/org/apache/cayenne/access/PrefetchProcessorNode.java
cayenne-server/src/main/java/org/apache/cayenne/access/PrefetchProcessorTreeBuilder.java
cayenne-server/src/main/java/org/apache/cayenne/access/ResultScanParentAttachmentStrategy.java
cayenne-server/src/main/java/org/apache/cayenne/access/StackLookupParentAttachmentStrategy.java
cayenne-server/src/test/java/org/apache/cayenne/access/JointPrefetchIT.java
cayenne-server/src/test/java/org/apache/cayenne/util/DeepMergeOperationIT.java

This PR changes the logic of prefetch attachment to the parent object. After these changes prefetch won't override related objects if there is a pending diff for that relationship in the context.
This could lead to incompatibility for any code relying on the old behaviour.

CAY-2630 Prefetched relationships not preserving pending changes

---

pom.xml

Eclipse maven integration (m2e) - add two missing goals to prevent errors on project
There were errors on the project like 'Plugin execution not covered by lifecycle configuration'

Eclipse maven integration (m2e) - add two missing goals to prevent errors

---

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/PreferenceDialog.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/templateeditor/FileTemplateSaver.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/templateeditor/PreviewGenerationAction.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/templateeditor/TemplateEditorController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/templateeditor/TemplateEditorView.java

- fix bug with duplicating template preview text
- Change EditorView from JDialog to JFrame. It's add some more functionality for template editor window (resize, collapse).

Update for template editor

---

cayenne-gradle-plugin/src/test/java/org/apache/cayenne/tools/GradlePluginIT.java

Fixed gradle version for java 19 as 7.6 is still a RC. It needs to be updated after release.

CAY-2776 Upgrade Gradle to 7.6

---

cayenne-project/src/test/java/org/apache/cayenne/project/upgrade/handlers/UpgradeHandler_V11Test.java

Made template line separator system-dependent as [```org.apache.cayenne.project.upgrade.handlers.UpgradeHandler_V11Test#testCgenDomUpgrade```](https://github.com/apache/cayenne/blob/3ffce18844e39e3801e6174929e71eda6d25efb9/cayenne-project/src/test/java/org/apache/cayenne/project/upgrade/handlers/UpgradeHandler_V11Test.java#L81) had failed for me locally on Windows.

Fix line separator for template

---

cayenne-ant/src/main/java/org/apache/cayenne/tools/CayenneGeneratorTask.java
cayenne-ant/src/test/java/org/apache/cayenne/tools/CayenneGeneratorTaskTest.java
cayenne-cgen/src/main/java/org/apache/cayenne/gen/CgenConfigList.java
cayenne-cgen/src/main/java/org/apache/cayenne/gen/CgenConfiguration.java
cayenne-cgen/src/main/java/org/apache/cayenne/gen/TemplateType.java
cayenne-cgen/src/main/java/org/apache/cayenne/gen/xml/CgenConfigHandler.java
cayenne-cgen/src/main/java/org/apache/cayenne/gen/xml/CgenSaverDelegate.java
cayenne-gradle-plugin/src/main/java/org/apache/cayenne/tools/CgenTask.java
cayenne-gradle-plugin/src/test/java/org/apache/cayenne/tools/CgenTaskTest.java
cayenne-server/src/main/resources/org/apache/cayenne/schema/11/cgen.xsd
maven-plugins/cayenne-maven-plugin/src/main/java/org/apache/cayenne/tools/CayenneGeneratorMojo.java
maven-plugins/cayenne-maven-plugin/src/test/java/org/apache/cayenne/tools/CayenneGeneratorMojoTest.java
modeler/cayenne-modeler-generic-ext/src/main/java/org/apache/cayenne/modeler/generic/GenericPlatformInitializer.java
modeler/cayenne-modeler-mac-ext/src/main/java/org/apache/cayenne/modeler/osx/OSXPlatformInitializer.java
modeler/cayenne-modeler-win-ext/src/main/java/org/apache/cayenne/modeler/win/WinPlatformInitializer.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/CheckBoxHeader.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/ClassesTabController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/ClassesTabPanel.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/CodeGeneratorController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/CodeGeneratorPane.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/SelectionModel.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/StandardModeController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/StandardModePanel.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/domain/CgenTabController.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/templateeditor/EditorTemplateSaver.java
modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/cgen/templateeditor/TemplateEditorController.java

We can now store multiple configurations to generate classes.
**How it works:**
1. You can add/rename/delete configurations in the class generation panel for the selected data map (select the data map in the left panel, see fig.1).
2. You can start the class generation with the selected configuration in this panel. Other configurations will not be used.
3. In case you need to generate classes for all your datamaps and configurations, you can do it in the project level class generation panel (select the project in the left panel, see fig.3). All configurations will be used for the selected datamaps.
4. Multiple configurations are also available when using Maven/Ant/Gdradle plugins.
5. If you do not need to use multiple configurations, then no extra steps are required. Default configuration …

CAY-2780 Multiple configurations for classes generation

---

cayenne-server/src/main/java/org/apache/cayenne/access/translator/select/DbPathProcessor.java
cayenne-server/src/main/java/org/apache/cayenne/exp/ExpressionFactory.java
cayenne-server/src/test/java/org/apache/cayenne/exp/ExpressionFactoryIT.java

Obj expression example:
```java
ExpressionFactory.matchAllExp("|paintingArray.toGallery.galleryName", "g1", "g2")
```
Db expression example:
```java
ExpressionFactory.matchAllExp("db:|paintingArray.toGallery.GALLERY_NAME", "g1", "g2")
```

CAY-2764 Split expressions do not work with DB relationships

---

RELEASE-NOTES.txt
cayenne-server/src/main/java/org/apache/cayenne/access/DataDomainQueryAction.java
cayenne-server/src/main/java/org/apache/cayenne/util/ObjectContextQueryAction.java
cayenne-server/src/test/java/org/apache/cayenne/cache/QueryCacheIT.java

This problem also affects the shared query cache.

CAY-2748 Mutating the list returned from the local query cache changes the cache

---

cayenne-cgen/src/main/java/org/apache/cayenne/gen/PropertyUtils.java
cayenne-cgen/src/test/resources/templateTest/_auto/_ObjEntity.java
cayenne-server/src/main/java/org/apache/cayenne/exp/property/PropertyFactory.java
cayenne-server/src/main/java/org/apache/cayenne/exp/property/SelfProperty.java
cayenne-server/src/test/java/org/apache/cayenne/exp/property/SelfPropertyTest.java
cayenne-server/src/test/java/org/apache/cayenne/query/ColumnSelectIT.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_ArtGroup.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_Artist.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_ArtistCallback.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_ArtistExhibit.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_CompoundPainting.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_CompoundPaintingLongNames.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_Exhibit.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_Gallery.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_MeaningfulGeneratedColumnTestEntity.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_NullTestEntity.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_Painting.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_Painting1.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_PaintingInfo.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_ROArtist.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_ROPainting.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_RWCompoundPainting.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/testmap/auto/_SubPainting.java

Here are some usage examples of the methods added:
```java
// query() method to create ObjectSelect
List<Artist> artistList = Artist.SELF.query().select(context);
// same with a where clause
Artist artistById = Artist.SELF.query(Artist.SELF.eqId(1)).selectOne(context);
// shortcut for a EXISTS/NOT EXISTS subquery 
long count = Artist.SELF.query(Painting.SELF.notExists(Painting.TO_ARTIST.eq(Artist.SELF.enclosing()))).selectCount(context);
// column select
List<String> names = Artist.SELF.columnQuery(Artist.ARTIST_NAME).select(context);
```

CAY-2759 Add utility methods to the SELF property

---

cayenne-server/src/main/java/org/apache/cayenne/value/json/JsonTokenizer.java
cayenne-server/src/test/java/org/apache/cayenne/value/json/JsonTokenizerTest.java

Fixed JsonTokenizer throwing MalformedJsonException because of trailing whitespace characters.

CAY-2789 MalformedJsonException thrown when reading manually edited JSON data in Postgres

---

cayenne-server/src/test/java/org/apache/cayenne/access/VerticalInheritanceIT.java
cayenne-server/src/test/java/org/apache/cayenne/testdo/inheritance_vertical/auto/_IvImpl.java
cayenne-server/src/test/resources/inheritance-vertical.map.xml

Breaking test for [CAY-2794](https://issues.apache.org/jira/browse/CAY-2794)
All I had to do was add a Date attribute to `IvImpl`, and one of the existing tests failed. But I did go ahead and set that attribute to a Date value, just so someone doesn't decide to remove that attribute in the future.
Still looking for a solution.

CAY-2794 Fix Incorrect JavaType for Vertical-Inheritance Attributes

---

cayenne-server/src/test/resources/relationships-flattened.map.xml

Running tests for DB2 fails with [DB2 -542 error](https://www.sqlerror.de/db2_sql_error_-542_sqlstate_42831.html). The reason is nullable db-attributes which are included in unique index because of 1-to-1 relationship. Making them not null is the simplest solution.

DB2 cannot build relationships-flattened test project

---

RELEASE-NOTES.txt
cayenne-commitlog/src/test/java/org/apache/cayenne/commitlog/CommitLogFilterIT.java
cayenne-server/src/main/java/org/apache/cayenne/BaseDataObject.java
cayenne-server/src/test/java/org/apache/cayenne/CDOOne2ManyIT.java
cayenne-server/src/test/java/org/apache/cayenne/CDOOneDep2OneIT.java

breaking tests and fix for [CAY-2851](https://issues.apache.org/jira/browse/CAY-2851)
also updated the test in `CommitLogFilterIT.testPostCommit_UpdateToOne` to account for the actual changes

CAY-2851 Replace Existing OneToOne From New Object

---

RELEASE-NOTES.txt
cayenne/src/main/java/org/apache/cayenne/access/ObjectStore.java
cayenne/src/main/java/org/apache/cayenne/access/flush/RootRowOpProcessor.java
cayenne/src/test/java/org/apache/cayenne/access/DataContextFlattenedAttributesIT.java

When deleting an ObjEntity with flattened attributes Cayenne deletes the related DB attribute's row as well.
So if we have for example an ObjEntity "FlatPainting" with flattened attribute "galleryName". If we then delete a "FlatPainting" then the associated gallery will also be deleted, leaving all other paintings at that gallery without a valid Gallery link.
Furthermore if we add to our "FlatPainting" a "gallery" relationship attribute with delete rule Deny, the gallery was still being deleted.
The original intention was for something like a "PaintingFull" ObjEntity having all painting attributes and a flattened attribute to "PaintingInfo" as well, where the relationship is 1:1. In this case it makes sense that deleting a "PaintingFull" should also delete its associated PaintingInfo …

CAY-2853 Incorrect deletion of entities from flattened attributes

---

RELEASE-NOTES.txt
cayenne/src/main/java/org/apache/cayenne/access/ObjectResolver.java
cayenne/src/main/java/org/apache/cayenne/access/ObjectStore.java
cayenne/src/main/java/org/apache/cayenne/access/flush/RootRowOpProcessor.java
cayenne/src/main/java/org/apache/cayenne/reflect/AdditionalDbEntityDescriptor.java
cayenne/src/main/java/org/apache/cayenne/reflect/ClassDescriptor.java
cayenne/src/main/java/org/apache/cayenne/reflect/LazyClassDescriptorDecorator.java
cayenne/src/main/java/org/apache/cayenne/reflect/PersistentDescriptor.java
cayenne/src/main/java/org/apache/cayenne/reflect/PersistentDescriptorFactory.java

Weather a flattened attribute row should/should not be deleted is currently detected each time during each delete query construction (see [PR 614](https://github.com/apache/cayenne/pull/614)).
In order to optimize the above repetitive process this PR moves the detection code into `PersistentDescriptorFactory` and sets a marker in `CayennePath` if needed to prevent the deletion of flattened attribute rows.

CAY-2854 Improve delete prevention detection of flattened attribute row

---

RELEASE-NOTES.txt
cayenne/src/main/java/org/apache/cayenne/access/translator/select/OrderingAbstractStage.java
cayenne/src/test/java/org/apache/cayenne/access/translator/select/OrderingStageTest.java

The current implementation has three problems:
1. It fails when a column has an alias
2. It builds the whole SQL column string before comparing
3. It doesn't seem very robust in preventing false results
This PR replaces the current implementation with a visitor pattern that fails fast.
The visitor extracts each node's parts into a List which is progressively compared to the parts extracted from the order node.
Each item must match in position and content in both lists for them to match and will abort comparing as soon as possible.

CAY-2847 Improve duplicate select column detection when using order by

---

cayenne/src/main/java/org/apache/cayenne/access/translator/select/QualifierTranslator.java
cayenne/src/main/java/org/apache/cayenne/dba/hsqldb/HSQLTreeProcessor.java
cayenne/src/main/java/org/apache/cayenne/exp/Expression.java
cayenne/src/main/java/org/apache/cayenne/exp/ExpressionFactory.java
cayenne/src/main/java/org/apache/cayenne/exp/parser/ASTCaseWhen.java
cayenne/src/main/java/org/apache/cayenne/exp/parser/ASTElse.java
cayenne/src/main/java/org/apache/cayenne/exp/parser/ASTThen.java
cayenne/src/main/java/org/apache/cayenne/exp/parser/ASTWhen.java
cayenne/src/main/java/org/apache/cayenne/exp/parser/AggregateConditionNode.java
cayenne/src/test/java/org/apache/cayenne/exp/AggregateExpInMemoryEvaluationIT.java
cayenne/src/test/java/org/apache/cayenne/exp/CaseWhenIT.java
cayenne/src/test/java/org/apache/cayenne/exp/ExpressionTest.java

PR brings support for the `CASE-WHEN` SQL operator to the Cayenne expression API.
Usage example (from the test):
```java
Expression caseWhen = ExpressionFactory.caseWhen(
List.of(Artist.PAINTING_ARRAY.dot(Painting.ESTIMATED_PRICE).between(BigDecimal.ZERO, BigDecimal.valueOf(50)),
Artist.PAINTING_ARRAY.dot(Painting.ESTIMATED_PRICE).between(BigDecimal.valueOf(51), BigDecimal.valueOf(100))),
List.of(Artist.ARTIST_NAME.getExpression(),
Artist.DATE_OF_BIRTH.getExpression()));
```
This PR supersedes  #593

CAY-2597 `case-when` implementation

---

RELEASE-NOTES.txt
cayenne-lifecycle/src/test/java/org/apache/cayenne/lifecycle/relationship/ObjectIdRelationshipHandlerTest.java
cayenne-server/src/main/java/org/apache/cayenne/access/ObjectDiff.java
cayenne-server/src/main/java/org/apache/cayenne/access/ObjectStore.java
cayenne-server/src/main/java/org/apache/cayenne/access/ObjectStorePersistentWrapper.java

Fix adds `ObjectStorePersistentWrapper` class that stores `Persistent` object with flatten paths in the same map, so it could be reclaimed by the GC.
This class implements `Persistent` interface for the maximum compatibility. And there are no changes to the public API (aside from the new class introduced). 
There is still a minor risk of incompatibility as someone could rely on `ObjectStore` exact internal structure.

CAY-2876 Memory leak in the ObjectStore
