apache/cayenne

cayenne-server/src/main/java/org/apache/cayenne/CayenneDataObject.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneDataObjectSetToManyCollectionTest.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneDataObjectSetToManyListTest.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneDataObjectSetToManyMapTest.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneDataObjectSetToManySetTest.java
This pull request extends the CayenneDataObject with a setToManyTarget(String, Collection<? extends DataObject>, boolean) method.
=> setToManyTarget

cayenne-server/src/main/java/org/apache/cayenne/access/translator/ParameterBinding.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/batch/DeleteBatchTranslator.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/batch/InsertBatchTranslator.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/batch/SoftDeleteBatchTranslator.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/batch/UpdateBatchTranslator.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/select/QueryAssembler.java, cayenne-server/src/main/java/org/apache/cayenne/access/translator/select/QueryAssemblerHelper.java, cayenne-server/src/main/java/org/apache/cayenne/dba/oracle/Oracle8LOBBatchTranslator.java, cayenne-server/src/test/java/org/apache/cayenne/access/translator/select/QualifierTranslatorIT.java
CAY-2050 Refactoring: ParameterBinding to contain ExtendedType property
=> CAY-2050 Refactoring: ParameterBinding to contain ExtendedType property

cayenne-server/src/main/java/org/apache/cayenne/query/Ordering.java
I've added an instance method to get a new List (ordered) off of an Ordering.  I just find this convenient to use when assigning to variables (without having to have extra code to modify the original List, which isn't always desired).
I've also added a static method to match how "orderList" was implemented.
=> Added instance and static orderedList methods

cayenne-server/src/main/java/org/apache/cayenne/map/Procedure.java, cayenne-server/src/main/resources/org/apache/cayenne/schema/8/modelMap.xsd, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/CreateProcedureAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/ProcedureTab.java
also added missing stored procedure parameters in the XSD
CAY-2075
=> CAY-2074 Support for catalogs in stored procedures

cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/BigDecimalConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/BigIntegerConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DefaultValueTransformerFactory.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DoubleConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/FloatConverter.java, cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/BigDecimalConverterTest.java, cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/BigIntegerConverterTest.java, cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/DoubleConverterTest.java, cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/FloatConverterTest.java
big integer and big decimal converters
=> CAY-2103 cayenne-crypto: support for mapping non-String and non-binary types

cayenne-crypto/src/main/java/org/apache/cayenne/crypto/CryptoModuleBuilder.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/Base64StringConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/BooleanConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/BytesToBytesConverter.java, cayenne-crypto/src/main/java/org/apache/cayenne/crypto/transformer/value/DefaultValueTransformerFactory.java, cayenne-crypto/src/test/java/org/apache/cayenne/crypto/transformer/value/DefaultValueTransformerFactoryIT.java
=> CAY-2106: cayenne-crypto: allow DI contribution of type converters inside ValueTransformerFactory

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/DefaultActionManager.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/ImportDataMapAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/DbImportProjectSaver.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/db/DbLoaderHelper.java
Datamap xml file was missing after removing and adding new data map via reverse engineering or importing
=> Modeler. Datamap xml file was missing after removing and adding new data map

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/db/MergerOptions.java
JdbcAdapter changed to more generic DbAdapter
=> Modeler migrate dialog adapter selection fix

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/CreateEmbeddableAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/datamap/PackageUpdateController.java
Fixed naming problems with Embeddable creation
Fixed ConcurrentModificationException on updating Embeddable package
=> Modeler. Problems with Embeddable naming

docs/doc/pom.xml, modeler/cayenne-modeler-generic-ext/pom.xml, modeler/cayenne-modeler-generic-ext/src/main/java/org/apache/cayenne/modeler/generic/GenericPlatformInitializer.java, modeler/cayenne-modeler-win-ext/pom.xml, modeler/cayenne-modeler-win-ext/src/main/java/org/apache/cayenne/modeler/win/WinCayenneModelerModule.java, modeler/cayenne-modeler-win-ext/src/main/java/org/apache/cayenne/modeler/win/WinMain.java, modeler/cayenne-modeler-win-ext/src/main/java/org/apache/cayenne/modeler/win/WinPlatformInitializer.java, modeler/cayenne-modeler-win/pom.xml, modeler/cayenne-modeler/pom.xml, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/db/DbLoaderOptionsDialog.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/objentity/ObjAttributeInfoDialogView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/EditorView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/DbEntityTab.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/PathChooserComboBoxCellEditor.java, modeler/pom.xml, pom.xml
- new Look&Feel selection for Windows
- PK generator renamed from "Default" to "Cayenne-Generated"
- fix for DB path selection in object attribute edit
- modeler specific dependencies version update
=> Modeler. Win Look&Feel and minor improvements

cayenne-server/src/main/java/org/apache/cayenne/access/dbsync/BaseSchemaUpdateStrategy.java
Hi @andrus 
I'm having an NPE on unboxing `threadRunInProgress`
=> NPE in BaseSchemaUpdateStrategy

cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/naming/DefaultObjectNameGenerator.java, cayenne-project/src/main/java/org/apache/cayenne/project/validation/BaseQueryValidator.java, cayenne-project/src/main/java/org/apache/cayenne/project/validation/ProcedureQueryValidator.java, cayenne-project/src/main/java/org/apache/cayenne/project/validation/SQLTemplateValidator.java, cayenne-project/src/main/java/org/apache/cayenne/project/validation/SelectQueryValidator.java, cayenne-server/src/main/java/org/apache/cayenne/map/MappingCache.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/CayenneModelerController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/FileClassLoadingService.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/ChangeObjEntityListenerClassAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/graph/DbGraphBuilder.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/DefaultWidgetFactory.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/PathChooserComboBoxCellEditor.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/WidgetFactory.java
- Exception in Infer relationships
- MappingCache: skip query descriptor name uniqueness check
- Update query name validator to check name uniqueness across all data maps
- Fix db path selection in ObjAttribute
- NPE in graph builder in process of reverse engineering
- Code clean up
=> Modeler. Pack of fixes

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/DataSourcePreferences.java
=> Modeler. Fixed Data Source test can be invalid in some cases

docs/doc/src/main/resources/RELEASE-NOTES.txt, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/DbEntityTab.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/PKCustomSequenceGeneratorPanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/PKDBGeneratorPanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/PKDefaultGeneratorPanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/dbentity/PKGeneratorPanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/undo/ChangePKGeneratorUndoableEdit.java
**Fix details**: 
- UI is updated correctly 
- added undo support for generator type change
=> CAY-2150 UI bug: PK generation custom sequence is getting reset

cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/merge/AddColumnToDb.java, cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/merge/DropColumnToDb.java, cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/merge/DropRelationshipToDb.java, docs/doc/src/main/resources/RELEASE-NOTES.txt
Fix ensure this ordering:
- Add column before add foreign key
- Drop foreign key before drop column
=> CAY-2154 Migrate db: queries order

cayenne-server/src/main/java/org/apache/cayenne/access/HierarchicalObjectResolver.java
Optimize parameters of queries generated by disjoin by id prefetch
=> CAY-2141 Disjoint-by-id prefetch generates repeating ID conditions 

.travis.yml, cayenne-server/src/test/resources/simplelogger.properties, pom.xml
Also provide property for passing log level in test.
=> Disable logs in all modules. 

cayenne-dbsync/src/main/java/org/apache/cayenne/dbsync/naming/NameUtil.java
=> removed repetitive code

cayenne-server/src/main/java/org/apache/cayenne/ejbql/parser/Compiler.java, cayenne-server/src/test/java/org/apache/cayenne/ejbql/EJBQLParser_CompileIT.java, docs/doc/src/main/resources/RELEASE-NOTES.txt
=> CAY-2175 AliasName used in EJBQLQuery is not working if it contains mixed case

cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClassGenerationAction.java, cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClientClassGenerationAction.java, docs/doc/src/main/resources/RELEASE-NOTES.txt, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/GeneratorController.java
+ exception throw on discrepancy of code generation parameters
=> CAY-2161 Fixed class generation with 'Not for client use' parameter

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/SelectQueryMainTab.java
=> CAY-2293 Object Select Query: Qualifier field can't be empty after the change

cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerAdapter.java, cayenne-server/src/main/java/org/apache/cayenne/dba/sybase/SybaseAdapter.java, cayenne-server/src/main/java/org/apache/cayenne/exp/Property.java, cayenne-server/src/main/java/org/apache/cayenne/query/Ordering.java, cayenne-server/src/main/java/org/apache/cayenne/query/Orderings.java
Sybase supports "identity" columns, so I've moved the call to setSupportsGeneratedKeys from SQLServerAdaptor to SybaseAdaptor (as the original comment suggested) and tested that it works.
=> Changed SybaseAdapter to allow identity (generated) columns

cayenne-cgen/src/main/resources/templates/v4_1/singleclass.vm, cayenne-cgen/src/main/resources/templates/v4_1/superclass.vm, cayenne-server/src/test/java/org/apache/cayenne/access/OptimisticLockingIT.java, cayenne-server/src/test/java/org/apache/cayenne/access/translator/batch/InsertBatchTranslatorIT.java, cayenne-server/src/test/java/org/apache/cayenne/testdo/locking/auto/_SimpleLockingTestEntity.java, cayenne-server/src/test/java/org/apache/cayenne/testdo/primitive/auto/_PrimitivesTestEntity.java, cayenne-server/src/test/resources/cayenne-locking.xml, cayenne-server/src/test/resources/cayenne-primitive.xml, cayenne-server/src/test/resources/locking.map.xml, cayenne-server/src/test/resources/primitive.map.xml, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/CodeTemplateManager.java
See [CAY-2369](https://issues.apache.org/jira/browse/CAY-2369)
=> CAY-2369 Compatibility issue with field-based data objects

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/ProjectTreeView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/graph/BaseGraphBuilder.java
Related to no particular issue. This is a behavior-preserving refactoring.
Summary of this pull request:
•	We are evaluating a research prototype called Bandago that assists in the refactoring of complex methods. Bandago is an Eclipse plugin that automatically identifies and refactors a type of code smell called Brain Method. A Brain Method centralizes the intelligence of a class and manifests itself as a long and complex method that is difficult to understand and maintain We have applied Bandago to 2 complex methods of your project, and we would like to receive feedback.
•	Bandago is very conservative and you should not observe many source code changes (only in the affected class).
•	The source code (after the refactoring) should behave equivalently to the original one.
•	As a sanity …
=> Refactoring complex methods of classes BaseGraphBuilder and ProjectTreeView

RELEASE-NOTES.txt, cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClassGenerationAction.java, cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClientClassGenerationAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/CodeTemplateManager.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/GenerateCodeAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/ClassesTabController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/ClassesTabPanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/ClientModeController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CodeGeneratorController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CodeGeneratorControllerBase.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CodeGeneratorDialog.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CustomModeController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/CustomModePanel.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/GeneratorController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/GeneratorTabController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/StandardModeController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/codegen/StandardModePanel.java
CAY-2479 Modeler: update cgen dialog
CAY-2476 Modeler: Fixed wrong behaviour of code generation dialog
=> CAY-2479, CAY-2476

cayenne-server/src/main/java/org/apache/cayenne/CayenneException.java, cayenne-server/src/main/java/org/apache/cayenne/CayenneRuntimeException.java, cayenne-server/src/main/java/org/apache/cayenne/access/jdbc/BatchAction.java, cayenne-server/src/main/java/org/apache/cayenne/access/jdbc/SQLTemplateAction.java, cayenne-server/src/main/java/org/apache/cayenne/access/types/ByteArrayType.java, cayenne-server/src/main/java/org/apache/cayenne/access/types/CharType.java, cayenne-server/src/main/java/org/apache/cayenne/access/util/IteratedSelectObserver.java, cayenne-server/src/main/java/org/apache/cayenne/dba/oracle/Oracle8LOBBatchAction.java, cayenne-server/src/main/java/org/apache/cayenne/dba/oracle/OracleBatchAction.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneExceptionTest.java, cayenne-server/src/test/java/org/apache/cayenne/CayenneRuntimeExceptionTest.java, cayenne-server/src/test/java/org/apache/cayenne/ConfigExceptionTest.java, cayenne-server/src/test/java/org/apache/cayenne/util/UtilTest.java
Removed usage of CayenneException. CayenneException marked as deprecated.
=> CAY-2487 Removed usage of CayenneException.

cayenne-server/src/main/java/org/apache/cayenne/reflect/BeanAccessor.java
Simplifies creation of BeanAccessor subclasses made solely to modify accessor method names.
=> New BeanAccessor constructor, allowing custom accessor method names

cayenne-jcache/pom.xml, cayenne-jcache/src/main/java/org/apache/cayenne/jcache/JCacheQueryCache.java, cayenne-jcache/src/test/java/org/apache/cayenne/jcache/unit/CacheServerRuntimeProvider.java, cayenne-jcache/src/test/resources/eh-cache.xml
A warning added when creating new cache entry with default config.
=> CAY-2642 EhCache memory leak due to misconfiguration

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/datanode/JDBCDataSourceView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/util/JTextFieldWhitespacesValidator.java
Validation spaces in JDBC Driver and DB URL lines in dataNode main window
=> CAY-2648 Space symbols in JDBC Driver and DB URL lines lead to incorrect driver loading

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/ClasspathPreferences.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/ClasspathPreferencesView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/MavenDependencyDialog.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/dialog/pref/MavenDependencyDialogView.java
This PR allows Modeler to download and add to classpath jars directly from Maven Central repo.
It doesn't mess with any maven stuff, downloaded jars stored to `~/.cayenne/modeler/` directory.
=> CAY-2656 Modeler: option to download required jars directly from maven central

cayenne-server/src/test/java/org/apache/cayenne/dba/ConcurrentPkGeneratorIT.java
in accordance with https://issues.apache.org/jira/browse/DERBY-7002 this increase may solve problem with similar exception
=> fix: increase derby.language.sequence.preallocator parameter to 1000

cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClassGenerationAction.java, cayenne-cgen/src/main/java/org/apache/cayenne/gen/ClassGeneratorResourceLoader.java
Solution for problem with finding templates on level above datamap.
=> CAY-2729 Unable to use custom templates from a folder at upper level then datamap

cayenne-server/src/main/java/org/apache/cayenne/BaseContext.java, cayenne-server/src/main/java/org/apache/cayenne/ObjectContext.java, cayenne-server/src/test/java/org/apache/cayenne/access/DataContextExtrasIT.java
CAY-2760 add new methods for removing user properties
=> CAY-2760 ObjectContext.userProperties need a way to clear properties

cayenne-server/src/main/java/org/apache/cayenne/dba/sqlserver/SQLServerAdapter.java
Add system catalogs for SQL Server to show dbo schema and hide system catalogs of dbo schema
=> CAY-2765 dbimport: check excluded catalogs and schemas for the SQLServer

modeler/cayenne-modeler/src/main/java/org/apache/cayenne/swing/components/textpane/TextPaneView.java
Replaced deprecated
```java
int drawUnselectedText(Graphics, int, int, int, int)
```
with
```java
float drawUnselectedText(Graphics2D, float, float, int, int)
```
and did some refactoring in [TextPaneView](https://github.com/apache/cayenne/blob/62b84421d773075bbb3348992754c32a2efa857f/modeler/cayenne-modeler/src/main/java/org/apache/cayenne/swing/components/textpane/TextPaneView.java).
=> CAY-2767 Modeler: upgrade deprecated code in custom components

cayenne-project/src/main/java/org/apache/cayenne/project/ConfigurationSourceSetter.java, cayenne-project/src/main/java/org/apache/cayenne/project/FileProjectSaver.java, cayenne-project/src/main/java/org/apache/cayenne/project/ProjectModule.java, cayenne-server/src/main/java/org/apache/cayenne/configuration/xml/XMLDataChannelDescriptorLoader.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/ProjectController.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/action/SaveAction.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/editor/DataMapView.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/event/ProjectSavedEvent.java, modeler/cayenne-modeler/src/main/java/org/apache/cayenne/modeler/event/ProjectSavedListener.java
- Now "file" field of datamap editor will be updated if name of file was changed and project was saved
- Added event and listener ProjectSaved, which are triggered when project is completely saved. Listener will update field value if location of datamap was changed
- Now if configuration source of datamap was updated location will be checked too
=> fix: datamap file field is not updated after Datamap renaiming

docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part1/mapping.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part1/modeler.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/customize.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/expressions.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/lifecycle.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/objectContext.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/starting.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part2/tuning.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part4/filtering.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part4/introduction.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part4/revEngineering.adoc, docs/asciidoc/cayenne-guide/src/docs/asciidoc/_cayenne-guide/part5/jCache.adoc
Hi there. I've found that there is a stuck progress on https://github.com/apache/cayenne-website/pull/21 - @cottage14 did a proof-reading on some docs, but published fixes in website repository. I've took those edits and carefully moved them to actual ASCIIdoc source files. Also I've rolled-back `Persistent` and couple more interface names as @andrus commented, and fixed some typos here and there for a good measure.
=> PR#21 on `cayenne-website` mirror in actual source

RELEASE-NOTES.txt, cayenne-commitlog/src/test/java/org/apache/cayenne/commitlog/CommitLogFilterIT.java, cayenne/src/main/java/org/apache/cayenne/PersistentObject.java, cayenne/src/test/java/org/apache/cayenne/CDOOne2ManyIT.java, cayenne/src/test/java/org/apache/cayenne/CDOOneDep2OneIT.java
=> CAY-2851 Replace Existing OneToOne From New Object

modeler/cayenne-modeler-generic-ext/src/main/java/org/apache/cayenne/modeler/generic/GenericPlatformInitializer.java, modeler/cayenne-modeler-win-ext/src/main/java/org/apache/cayenne/modeler/win/WinPlatformInitializer.java
=> [4.2] Modeler: Fix menu item background and foreground colors

cayenne/src/main/java/org/apache/cayenne/access/DataContextObjectCreator.java, cayenne/src/main/java/org/apache/cayenne/reflect/ArcProperty.java, cayenne/src/main/java/org/apache/cayenne/reflect/ClassDescriptor.java, cayenne/src/main/java/org/apache/cayenne/reflect/LazyClassDescriptorDecorator.java, cayenne/src/main/java/org/apache/cayenne/reflect/PersistentDescriptor.java, cayenne/src/main/java/org/apache/cayenne/reflect/PersistentDescriptorFactory.java, cayenne/src/main/java/org/apache/cayenne/util/DeepMergeOperation.java, cayenne/src/test/java/org/apache/cayenne/access/VerticalInheritanceIT.java, cayenne/src/test/java/org/apache/cayenne/reflect/generic/PersistentObjectDescriptorFactory_VerticalInheritanceIT.java, cayenne/src/test/resources/inheritance-vertical.map.xml
This PR is based on #432, particularly it directly uses test cases from it
=> CAY-2667 Fix Issues with Generic Vertical Inheritance
